# Ghost-Linux Calamares Installer Configuration Settings
---
modules-search: [ local ]

instances:
  - id:       ghost-linux-branding
    module:   branding
    config:   branding.desc

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - postcfg
    - umount
  - show:
    - finished

branding: ghost-linux
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-sending-ok-to-distributor: true
show-back-on-finished: false
