# Calamares partitioning configuration for Btrfs setups
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: EFI

# Default filesystem type
defaultFileSystemType: btrfs

availableFileSystemTypes:  ["btrfs", "ext4", "f2fs"]

# Btrfs Subvolumes structure
btrfsSubvolumes:
  - mountPoint: /
    subvolume: /@
  - mountPoint: /home
    subvolume: /@home
  - mountPoint: /var/cache
    subvolume: /@cache
  - mountPoint: /var/log
    subvolume: /@log
  - mountPoint: /.snapshots
    subvolume: /@snapshots

btrfsSwapSubvolume:
  subvolume: /@swap
  size: 8GiB

# Allow user to choose swap options
swapModes:
  - none
  - file
  - reuse
